/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentSubmitRouteImport } from './routes/student.submit'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as CertificateIdRouteImport } from './routes/certificate.$id'
import { Route as ApproverDashboardRouteImport } from './routes/approver.dashboard'
import { Route as ApiGenerateCertificateRouteImport } from './routes/api.generate-certificate'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminDuesRouteImport } from './routes/admin.dues'
import { Route as ApiStripeCreateCheckoutRouteImport } from './routes/api.stripe.create-checkout'
import { Route as ApiStripeConfirmPaymentRouteImport } from './routes/api.stripe.confirm-payment'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSubmitRoute = StudentSubmitRouteImport.update({
  id: '/student/submit',
  path: '/student/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateIdRoute = CertificateIdRouteImport.update({
  id: '/certificate/$id',
  path: '/certificate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproverDashboardRoute = ApproverDashboardRouteImport.update({
  id: '/approver/dashboard',
  path: '/approver/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCertificateRoute = ApiGenerateCertificateRouteImport.update({
  id: '/api/generate-certificate',
  path: '/api/generate-certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDuesRoute = AdminDuesRouteImport.update({
  id: '/admin/dues',
  path: '/admin/dues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCreateCheckoutRoute = ApiStripeCreateCheckoutRouteImport.update({
  id: '/api/stripe/create-checkout',
  path: '/api/stripe/create-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeConfirmPaymentRoute = ApiStripeConfirmPaymentRouteImport.update({
  id: '/api/stripe/confirm-payment',
  path: '/api/stripe/confirm-payment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/dues': typeof AdminDuesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/api/generate-certificate': typeof ApiGenerateCertificateRoute
  '/approver/dashboard': typeof ApproverDashboardRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/submit': typeof StudentSubmitRoute
  '/api/stripe/confirm-payment': typeof ApiStripeConfirmPaymentRoute
  '/api/stripe/create-checkout': typeof ApiStripeCreateCheckoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/dues': typeof AdminDuesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/api/generate-certificate': typeof ApiGenerateCertificateRoute
  '/approver/dashboard': typeof ApproverDashboardRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/submit': typeof StudentSubmitRoute
  '/api/stripe/confirm-payment': typeof ApiStripeConfirmPaymentRoute
  '/api/stripe/create-checkout': typeof ApiStripeCreateCheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/dues': typeof AdminDuesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/api/generate-certificate': typeof ApiGenerateCertificateRoute
  '/approver/dashboard': typeof ApproverDashboardRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/submit': typeof StudentSubmitRoute
  '/api/stripe/confirm-payment': typeof ApiStripeConfirmPaymentRoute
  '/api/stripe/create-checkout': typeof ApiStripeCreateCheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/admin/dues'
    | '/admin/payments'
    | '/api/generate-certificate'
    | '/approver/dashboard'
    | '/certificate/$id'
    | '/student/dashboard'
    | '/student/submit'
    | '/api/stripe/confirm-payment'
    | '/api/stripe/create-checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/admin/dues'
    | '/admin/payments'
    | '/api/generate-certificate'
    | '/approver/dashboard'
    | '/certificate/$id'
    | '/student/dashboard'
    | '/student/submit'
    | '/api/stripe/confirm-payment'
    | '/api/stripe/create-checkout'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/admin/dues'
    | '/admin/payments'
    | '/api/generate-certificate'
    | '/approver/dashboard'
    | '/certificate/$id'
    | '/student/dashboard'
    | '/student/submit'
    | '/api/stripe/confirm-payment'
    | '/api/stripe/create-checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AdminDuesRoute: typeof AdminDuesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  ApiGenerateCertificateRoute: typeof ApiGenerateCertificateRoute
  ApproverDashboardRoute: typeof ApproverDashboardRoute
  CertificateIdRoute: typeof CertificateIdRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentSubmitRoute: typeof StudentSubmitRoute
  ApiStripeConfirmPaymentRoute: typeof ApiStripeConfirmPaymentRoute
  ApiStripeCreateCheckoutRoute: typeof ApiStripeCreateCheckoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/submit': {
      id: '/student/submit'
      path: '/student/submit'
      fullPath: '/student/submit'
      preLoaderRoute: typeof StudentSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$id': {
      id: '/certificate/$id'
      path: '/certificate/$id'
      fullPath: '/certificate/$id'
      preLoaderRoute: typeof CertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approver/dashboard': {
      id: '/approver/dashboard'
      path: '/approver/dashboard'
      fullPath: '/approver/dashboard'
      preLoaderRoute: typeof ApproverDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-certificate': {
      id: '/api/generate-certificate'
      path: '/api/generate-certificate'
      fullPath: '/api/generate-certificate'
      preLoaderRoute: typeof ApiGenerateCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dues': {
      id: '/admin/dues'
      path: '/admin/dues'
      fullPath: '/admin/dues'
      preLoaderRoute: typeof AdminDuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/create-checkout': {
      id: '/api/stripe/create-checkout'
      path: '/api/stripe/create-checkout'
      fullPath: '/api/stripe/create-checkout'
      preLoaderRoute: typeof ApiStripeCreateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/confirm-payment': {
      id: '/api/stripe/confirm-payment'
      path: '/api/stripe/confirm-payment'
      fullPath: '/api/stripe/confirm-payment'
      preLoaderRoute: typeof ApiStripeConfirmPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AdminDuesRoute: AdminDuesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  ApiGenerateCertificateRoute: ApiGenerateCertificateRoute,
  ApproverDashboardRoute: ApproverDashboardRoute,
  CertificateIdRoute: CertificateIdRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentSubmitRoute: StudentSubmitRoute,
  ApiStripeConfirmPaymentRoute: ApiStripeConfirmPaymentRoute,
  ApiStripeCreateCheckoutRoute: ApiStripeCreateCheckoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
